.job_template: &job_definition
  type: test
  script:
  - node -v
  - npm install
  - npm test
  - cat /proc/cpuinfo | grep "^model name" | uniq
  - npm run-script bench

before_script:
  - uname -a

types:
  - test
  - release

node-latest:
  image: node:latest
  <<: *job_definition

release:
  type: release
  image: node:latest
  script:
  - echo ${NPM_TOKEN} > ~/.npmrc
  - npm publish
  only:
  - tags
